version: '3.8'

services:
  # Next.js application
  app:
    image: ghcr.io/monokaijs/tower:latest
    container_name: tower-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/tower
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your_nextauth_secret_key_here
      # Add other environment variables as needed
      # - GOOGLE_CLIENT_ID=
      # - GOOGLE_CLIENT_SECRET=
    depends_on:
      - mongo
    networks:
      - tower-network

  # MongoDB database
  mongo:
    image: mongo:latest
    container_name: tower-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tower-network

  # MongoDB Express admin interface
  mongo-express:
    image: mongo-express:latest
    container_name: tower-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      # For production with authentication
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
    networks:
      - tower-network

networks:
  tower-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
